### ISSUE TITLE
pip install -r requirements.txt fail 

### ISSUE THREAD

**Issue by azuryl** [abhinavagarwalla/model-inversion-3d#1]
Dear @abhinavagarwalla 
Thank of your great job .I want to run  CenterNet_inversion.ipynb
according to README  "refer to the folder `Pointnet_Pointnet2_pytorch` for inverting 3D detection model".
so I  pip install -r requirements.txt
but 

ERROR: git+git@github.com:abhinavagarwalla/Open3D-ML.git@1b3c961c535f84e7ab353e952bfcd770b7939678#egg=ml3d is not a valid editable requirement. It should either be a path to a local project or a VCS URL (beginning with bzr+http, bzr+https, bzr+ssh, bzr+sftp, bzr+ftp, bzr+lp, bzr+file, git+http, git+https, git+ssh, git+git, git+file, hg+file, hg+http, hg+https, hg+ssh, hg+static-http, svn+ssh, svn+http, svn+https, svn+svn, svn+file).

**Comment by abhinavagarwalla** [comment]
Thank you for your interest.
That's a typo in the README. For running just the 3D detection part, `vis_det` folder has all the code.  There is no need to install anything in `Pointnet_Pointnet2_pytorch`. I will correct the README.
